services:
  postgres-users:
    image: postgres:16
    container_name: elib-postgres-users
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elibrary_users
    ports:
      - "5433:5432"
    volumes:
      - postgres_users_data:/var/lib/postgresql/data

  postgres-books:
    image: postgres:16
    container_name: elib-postgres-books
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elibrary_books
    ports:
      - "5434:5432"
    volumes:
      - postgres_books_data:/var/lib/postgresql/data

  postgres-borrows:
    image: postgres:16
    container_name: elib-postgres-borrows
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elibrary_borrows
    ports:
      - "5435:5432"
    volumes:
      - postgres_borrows_data:/var/lib/postgresql/data

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8087:8087"
      - "50051:50051"
    environment:
      HTTP_PORT: 8087
      GRPC_PORT: 50051
      USER_DB_URL: postgres://postgres:postgres@postgres-users:5432/elibrary_users?sslmode=disable
    depends_on:
      - postgres-users

  book-service:
    build:
      context: ./book-service
    container_name: book-service
    ports:
      - "8088:8088"
      - "50052:50052"
    environment:
      HTTP_PORT: 8088
      GRPC_PORT: 50052
      BOOK_DB_URL: postgres://postgres:postgres@postgres-books:5432/elibrary_books?sslmode=disable
    depends_on:
      - postgres-books

  borrow-service:
    build:
      context: ./borrow-service
    container_name: borrow-service
    ports:
      - "8089:8089"
      - "50053:50053"
    environment:
      HTTP_PORT: 8089
      GRPC_PORT: 50053
      BORROW_DB_URL: postgres://postgres:postgres@postgres-borrows:5432/elibrary_borrows?sslmode=disable
      NATS_URL: nats://nats:4222
    depends_on:
      - postgres-borrows
      - nats

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      API_GATEWAY_PORT: 8080
      USER_SERVICE_GRPC_ADDR: user-service:50051
      BOOK_SERVICE_GRPC_ADDR: book-service:50052
      BORROW_SERVICE_GRPC_ADDR: borrow-service:50053
    depends_on:
      - user-service
      - book-service
      - borrow-service

  redis:
    image: redis:7-alpine
    container_name: elib-redis
    ports:
      - "6379:6379"

  nats:
    image: nats:latest
    container_name: elib-nats
    ports:
      - "4222:4222"
   
  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    environment:
      NATS_URL: nats://nats:4222
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: your_email@gmail.com
      SMTP_PASSWORD: your_app_password
      SMTP_FROM: your_email@gmail.com
      SMTP_TO: your_email@gmail.com
      SMTP_ENABLED: "false"
    depends_on:
      - nats
      - borrow-service

volumes:
  postgres_users_data:
  postgres_books_data:
  postgres_borrows_data: