services:
  postgres-users:
    image: postgres:16
    container_name: elib-postgres-users
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elibrary_users
    ports:
      - "5433:5432"
    volumes:
      - postgres_users_data:/var/lib/postgresql/data

  postgres-books:
    image: postgres:16
    container_name: elib-postgres-books
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elibrary_books
    ports:
      - "5434:5432"
    volumes:
      - postgres_books_data:/var/lib/postgresql/data

  postgres-borrows:
    image: postgres:16
    container_name: elib-postgres-borrows
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elibrary_borrows
    ports:
      - "5435:5432"
    volumes:
      - postgres_borrows_data:/var/lib/postgresql/data

  borrow-service:
    build:
      context: ./borrow-service
    container_name: borrow-service
    ports:
      - "8089:8089"
      - "50053:50053"
    environment:
      HTTP_PORT: 8089
      GRPC_PORT: 50053
      BORROW_DB_URL: postgres://postgres:postgres@postgres-borrows:5432/elibrary_borrows?sslmode=disable
    depends_on:
      - postgres-borrows

volumes:
  postgres_users_data:
  postgres_books_data:
  postgres_borrows_data: