FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o book-service ./cmd

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/book-service .
COPY .env .

EXPOSE 8088
EXPOSE 50052

CMD ["./book-service"]